### ISSUE TITLE
Prometheus metric naming conventions

### ISSUE THREAD

**Issue by Nachtmerrie** [jordyv/prometheus-p1-exporter#1]
Hoi,

Zou je de metric namen aan willen passen volgens de regeltjes/best practices? 

https://prometheus.io/docs/practices/naming/

Dus allemaal prefixen met `dsmr_` of `p1_` :)

**Comment by jordyv** [comment]
Goed plan! Ik heb het gefixt, `p1_` is de prefix geworden. Thanks voor je suggestie.
