### ISSUE TITLE
make usb serial port configurable

### ISSUE THREAD

**Issue by markvdb** [jordyv/prometheus-p1-exporter#16]
Hello!

First of all, thank you for this very nice piece of free software.

You owe me absolutely nothing,  but I'd very much appreciate if you could make the usb serial device configurable. It's not always /dev/ttyUSB0...

Here's an anecdote. I tested your software on two laptops; same make, same model, same software stack. prometheus-p1-exporter worked on the first one but not on the second. Five seconds of head scratching. Turns out the second one had a modem on board. That made the usb serial device identify not as /dev/ttyUSB0, but as /dev/ttyUSB3 !

Thanks again for your work on free software. Much appreciated!

Mark

P.S. A more common scenario might be the device collecting the metrics reading logs from two usb serial ports...

**Comment by markvdb** [comment]
I initially hesitated to write any contribution in a language I'd never written in yet, but Go is fairly readable, so here you go: https://github.com/jordyv/prometheus-p1-exporter/pull/17 .

**Comment by jordyv** [comment]
Thanks! I merged your PR. 
Your first code in Go, who knows what this will bring you in the future 🙌🏻.
